git:
  depth: 1

branches:
  only:
    - master

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: none
      compiler: g++
    - os: osx
      osx_image: xcode9.2
      compiler: clang++

script:
  - mkdir build; cd build;
    if [ $TRAVIS_OS_NAME == linux ]; then cmake -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..; fi;
    if [ $TRAVIS_OS_NAME == osx ]; then cmake -G XCode -DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=YES ..; fi;
  - cmake --build . --config Release -- -j 2
